### ISSUE TITLE
Examples for SocketIO? (Client and server)

### ISSUE THREAD

**Issue by MatthijsKamstra** [MatthijsKamstra/haxenode#6]
Request from @TheoSabattie

I started it, but never finished it (https://github.com/MatthijsKamstra/haxenode/tree/master/12socket)

It is a big one to do, so probably the reason I didn't finish. 😞

**Comment by TheoSabattie** [comment]
Great! Thanks ! :+1: 

What is missing?

**Comment by MatthijsKamstra** [comment]
I am not sure... it been a while.
And currently not working with node.js
So I need to check it out what exactly is missing.

**Comment by MatthijsKamstra** [comment]
Okay tried to update the example to working order...
And ran into something unexpected:

```
if (process.version < "v4.0.0") console.warn("Module " + (typeof(module) == "undefined" ? "" : module.filename) + " requires node.js version 4.0.0 or higher");
```

Currently this only works with a little addition
```
if (typeof process !== 'undefined' ) if (process.version < "v4.0.0") console.warn("Module " + (typeof(module) == "undefined" ? "" : module.filename) + " requires node.js version 4.0.0 or higher");
```



read more about this here: https://github.com/clemos/haxe-js-kit/issues/141

**Comment by MatthijsKamstra** [comment]
Done : http://matthijskamstra.github.io/haxenode/12socket/example.html
